spring:
  profiles:
    active: local
server:
  port: 8081
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
#        acks = -1 = all
        acks: all
        retries: 10
        retry:
          backoff:
            ms: 1000
    admin:
      properties:
        bootstrap:
          servers: localhost:9091,localhost:9092,localhost:9093


---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prop:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
